export const ActionTypes = {
    PRODUCT_LIST: {
        GET_ALL_PRODUCTS: 'GET_ALL_PRODUCTS'
    },
    CART: {
        ADD_ITEM_INTO_CART: 'ADD_ITEM_INTO_CART',
        UPDATE_CART: 'UPDATE_CART'
    },
    PRODUCT_DETAILS: {
        GET_PRODUCT_DETAIL: 'GET_PRODUCT_DETAIL',
        CLEAR_PRODUCT_DETAILS: 'CLEAR_PRODUCT_DETAILS'
    }
};